services:
  postgres:
    image: postgres:16-alpine
    container_name: spark-postgres
    environment:
      POSTGRES_DB: spark_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spark_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
